language: ruby

rvm:
  - 2.4.1

before_script:
  - gem install awesome_bot

script:
  - grep ^### README.md > README.md-unique_urls
  - awesome_bot --allow-redirect README.md-unique_urls
  - awesome_bot --allow-dupe --allow-redirect README.md
