dist: xenial

language: python

services:
  - docker

node_js: 10

install:
  # Install markdownlint and markdown-link-check
  - npm install -g markdownlint-cli markdown-link-check > /dev/null

script:
  # Markdown check
  - find . -name "*.md" -print0 | xargs -0 markdownlint

  # Link Checks
  - find . -name "*.md" -print0 | xargs -0 markdown-link-check --quiet

  # Checking the duplicate Video Length values which should unlikely be the same
  - export DUPLICATE_VIDEO_LENGTH=`grep '* Video Length:' README.md | sort | uniq -d`
  - if `echo "${DUPLICATE_VIDEO_LENGTH}" | grep Video`; then echo -e "\n*** Found duplicate Video Length values which is probably copy&paste typo."; exit 1; else echo -e "\n*** Test OK"; fi

  # Check if the tutorials are properly sorted
  - grep "^###" README.md > /tmp/tutorials
  - grep "^###" README.md | sort --ignore-case --version-sort > /tmp/sorted_tutorials
  - if sdiff /tmp/tutorials /tmp/sorted_tutorials; then echo -e "\n*** Test OK"; else echo -e "\n*** Tutorials are not properly sorted!"; exit 1; fi

  # Check if the all screenshots are mentioned in main README file
  - for FILE in screenshots/*; do echo "*** $FILE"; grep "$FILE" README.md; done
