language: ruby

rvm:
  - 2.4.1

before_script:
  - gem install awesome_bot

script:
  # Getting the URLs ftom title which should be unique for sure
  - grep ^### README.md > /tmp/README.md-unique_urls
  - awesome_bot --allow-redirect /tmp/README.md-unique_urls

  # Checking the duplicate Video Length values which should unlikely be the same (except 04:21)
  - export DUPLICATE_VIDEO_LENGTH=`grep '* Video Length:' README.md | grep -v '04:21' | sort | uniq -d`
  - if `echo "${DUPLICATE_VIDEO_LENGTH}" | grep Video`; then echo -e "\n*** Found duplicate Video Length values which is probably copy&paste typo."; exit 1; else echo -e "\n*** Test OK"; fi

  # Checking all URLs
  - awesome_bot --allow-dupe --allow-redirect README.md

  # Check if the tutorials are properly sorted
  - grep "^###" README.md > /tmp/tutorials
  - grep "^###" README.md | sort --ignore-case --version-sort > /tmp/sorted_tutorials
  - if sdiff /tmp/tutorials /tmp/sorted_tutorials; then echo -e "\n*** Test OK"; else echo -e "\n*** Tutorials are not properly sorted!"; exit 1; fi
