name: checks

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

permissions: read-all

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Checking the duplicate Video Length values which should unlikely be the same
        run: |
          DUPLICATE_VIDEO_LENGTH=$(grep ' Video Length:' README.md | sort | uniq -d)
          if echo "${DUPLICATE_VIDEO_LENGTH}" | grep Video; then
            echo -e "\n*** Found duplicate Video Length values which is probably copy&paste typo."
          else
            echo -e "\n*** Test OK"
          fi

      - name: Check if the tutorials are properly sorted
        run: |
          grep "^###" README.md > /tmp/tutorials
          grep "^###" README.md | sort --ignore-case --version-sort > /tmp/sorted_tutorials
          if sdiff /tmp/tutorials /tmp/sorted_tutorials; then
            echo -e "\n*** Test OK"
          else
            echo -e "\n*** Tutorials are not properly sorted!"
            exit 1
          fi

      - name: Check if the all screenshots are mentioned in main README file
        run: |
          for FILE in screenshots/*; do
            if ! grep -q "$FILE" README.md; then
              echo "*** Missing $FILE in README.md"
            fi
          done
