name: periodic-markdown-links-check

on:
  schedule:
    - cron: '8 8 * * 1'

jobs:
  markdown-link-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
